---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rapierr

Bring Rapier 2D functionality to R

<!-- badges: start -->
<!-- badges: end -->

:warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning:

Don't expect this package to work at the moment.

:warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning:

## What is Rapier?

[Rapier](https://github.com/dimforge/rapier) is the 2D and 3D physics engines for the Rust programming language. 

## Installation

You can install the development version of rapierr like so:

``` r
remotes::install_github("yutannihilation/rapierr")
```

## Example

```{r bouncing_ball}
#| animation.hook: gifski
#| interval: !expr 1/60
#| dev: ragg_png
#| 
library(rapierr)
library(ggplot2)

world <- Rapier2DWorld$new()

# ground
world$add_fixed_segment(-50.0, 0.0, 50.0, 0.0, 0.70);

restitution_line <- 0.75
restitution_ball <- 0.95
r <- 0.02

world$add_ball(-0.4, 0.4, r,         restitution_ball)
world$add_line(-0.4, 0.4, -0.2, 0.7, restitution_line)
world$add_ball(-0.2, 0.7, r,         restitution_ball)
world$add_line(-0.2, 0.7, 0.0, 0.9,  restitution_line)
world$add_ball(0.0, 0.9, r,          restitution_ball)
world$add_line(0.0, 0.9, 0.2, 0.8,   restitution_line)
world$add_ball(0.2, 0.8, r,          restitution_ball)
world$add_line(0.2, 0.8, 0.4, 1.1,   restitution_line)
world$add_ball(0.4, 1.1, r,          restitution_ball)

d <- world$step(200)

p <- ggplot() +
  ggforce::geom_circle(data = \(x) dplyr::filter(x, index %% 2 == 0L),
                       aes(x0 = x, y0 = y, r = size), fill = "black") +
  geom_segment(data = \(x) dplyr::filter(x, index %% 2 == 1L),
               aes(x    = x - size * 0.5 * cos(angle),
                   y    = y - size * 0.5 * sin(angle),
                   xend = x + size * 0.5 * cos(angle),
                   yend = y + size * 0.5 * sin(angle))) +
  scale_size_identity() +
  coord_equal(xlim = c(-0.5, 0.5), ylim = c(0, 1.2)) +
  ggtitle("Falling trend. Yes, it's falling.") +
  theme_minimal() +
  theme(text = element_text(size = 20)) +
  labs(x = "X", y = "Y")

# repeat the first frame
for (i in 1:150) {
  plot(p %+% dplyr::filter(d, frame == 0L))
}


for (frame in seq_len(max(d$frame))) {
  plot(p %+% dplyr::filter(d, frame == {{ frame }}))
}
```

## Similar Projects

- [chipmunkcore](https://github.com/coolbutuseless/chipmunkcore)
