[package]
name = "rpr2dr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = "fat"

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr.git" }
rapier2d = { version = "*", features = ["simd-stable"] }
