# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rapierr_wrappers", use_symbols = TRUE, package_name = "rapierr")

#' @docType package
#' @usage NULL
#' @useDynLib rapierr, .registration = TRUE
NULL

#' The 2D World of Rapier
#'
#' @export
Rapier2DWorld <- new.env(parent = emptyenv())

Rapier2DWorld$new <- function() .Call(wrap__Rapier2DWorld__new)

Rapier2DWorld$step <- function(n) .Call(wrap__Rapier2DWorld__step, self, n)

Rapier2DWorld$add_ball <- function(x, y, radius, restitution) invisible(.Call(wrap__Rapier2DWorld__add_ball, self, x, y, radius, restitution))

Rapier2DWorld$add_line <- function(x0, y0, x1, y1, restitution) invisible(.Call(wrap__Rapier2DWorld__add_line, self, x0, y0, x1, y1, restitution))

Rapier2DWorld$add_fixed_segment <- function(x0, y0, x1, y1, restitution) invisible(.Call(wrap__Rapier2DWorld__add_fixed_segment, self, x0, y0, x1, y1, restitution))

Rapier2DWorld$object_count <- function() .Call(wrap__Rapier2DWorld__object_count, self)

#' @rdname Rapier2DWorld
#' @usage NULL
#' @export
`$.Rapier2DWorld` <- function (self, name) { func <- Rapier2DWorld[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Rapier2DWorld` <- `$.Rapier2DWorld`


# nolint end
