# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rapierr_wrappers", use_symbols = TRUE, package_name = "rapierr")

#' @docType package
#' @usage NULL
#' @useDynLib rapierr, .registration = TRUE
NULL

#' Return rapier results
#' @export
bouncing_ball <- function() .Call(wrap__bouncing_ball)


# nolint end
